# Generated by Django 6.0.6 on 2026-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('se', 'Software Engineering'), ('ai', 'AI & ML'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
