# Generated by Django 6.0.6 on 2026-06-12 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_community_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationpost',
            name='roles_needed',
            field=models.TextField(blank=True),
        ),
    ]
