# Generated by Django 6.0.6 on 2026-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_communitymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='message_permission',
            field=models.CharField(choices=[('all_members', 'All Members'), ('admins_only', 'Admins Only')], default='all_members', max_length=20),
        ),
        migrations.AddField(
            model_name='communitymember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
