# Generated by Django 6.0.6 on 2026-06-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_collaborationpostinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='by_line',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
