# Generated by Django 6.0.6 on 2026-06-15 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_announcement_options_announcement_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationpost',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentored_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborationpostinterest',
            name='status',
            field=models.CharField(choices=[('interested', 'Interested'), ('team', 'Team Member'), ('declined', 'Declined')], default='interested', max_length=20),
        ),
    ]
