# Generated by Django 6.0.6 on 2026-06-15 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_collaborationpost_mentor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.announcementcomment'),
        ),
        migrations.AddField(
            model_name='collaborationpostcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='core.collaborationpostcomment'),
        ),
    ]
