# Generated by Django 6.0.6 on 2026-06-15 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_comment_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
