# Generated by Django 6.0.6 on 2026-06-17 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_user_current_company_user_current_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymember',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('founder', 'Founder')], default='member', max_length=15),
        ),
        migrations.AddField(
            model_name='note',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CareerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('apply_url', models.URLField(blank=True)),
                ('opp_type', models.CharField(choices=[('internship', 'Internship'), ('job', 'Job')], default='internship', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
