# Generated by Django 6.0.6 on 2026-06-17 15:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_communitymember_role_note_semester_careeropportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mentorship_request', 'Mentorship Request'), ('mentorship_accepted', 'Mentorship Accepted'), ('mentorship_rejected', 'Mentorship Rejected'), ('new_message', 'New Message'), ('connection', 'New Connection'), ('community_join', 'Community Joined')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='collaborationmessage',
            name='file',
            field=models.FileField(blank=True, upload_to='collaboration_chat/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('cs', 'Computer Science'), ('se', 'Software Engineering'), ('ai', 'AI & ML'), ('general', 'General')], db_index=True, default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='communitymessage',
            name='file',
            field=models.FileField(blank=True, upload_to='community_chat/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='mentorshipmessage',
            name='file',
            field=models.FileField(blank=True, upload_to='mentorship_chat/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'txt'])]),
        ),
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, upload_to='notes/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'zip', 'rar'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('senior', 'Senior'), ('alumni', 'Alumni'), ('admin', 'Admin')], db_index=True, default='student', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['subject'], name='core_note_subject_142c79_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['-upload_date'], name='core_note_upload__6f841a_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
