from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('reset-password/', views.reset_password_view, name='reset_password'),
    path('logout/', views.logout_view, name='logout'),
    path('admin-panel/', views.admin_panel, name='admin_panel'),
    path('admin-api/', views.admin_api, name='admin_api'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/', views.profile_view, name='profile'),
    path('user/<int:user_id>/', views.user_profile_view, name='user_profile'),
    path('notes/', views.notes_view, name='notes'),
    path('communities/', views.communities_view, name='communities'),
    path('collaboration/', views.collaboration_view, name='collaboration'),
    path('chat/', views.chat_view, name='chat'),
    path('mentorship/', views.mentorship_view, name='mentorship'),
    path('alumni-directory/', views.alumni_directory_view, name='alumni_directory'),
    path('privacy/', views.privacy, name='privacy'),
    path('terms/', views.terms, name='terms'),
    path('contact/', views.contact, name='contact'),
    path('communities/<int:community_id>/chat/', views.community_chat_view, name='community_chat'),
    path('collaboration/<int:post_id>/chat/', views.collaboration_chat_view, name='collaboration_chat'),
    path('mentorship/<int:mentorship_id>/chat/', views.mentorship_chat_view, name='mentorship_chat'),
    path('api/user/<int:user_id>/', views.user_profile_api, name='user_profile_api'),
    path('api/alumni-list/', views.alumni_list_api, name='alumni_list_api'),
    path('api/send-mentorship-request/', views.send_mentorship_request_api, name='send_mentorship_request'),
    path('api/mentorship-requests/', views.mentorship_requests_api, name='mentorship_requests_api'),
    path('api/handle-mentorship-request/', views.handle_mentorship_request_api, name='handle_mentorship_request'),
    path('api/update-alumni-profile/', views.update_alumni_profile_api, name='update_alumni_profile'),
    path('api/notifications/', views.notifications_api, name='notifications_api'),
    path('api/notifications/unread-count/', views.unread_notification_count_api, name='unread_notification_count'),
]
